const ELEMENTS = [
  { number: 1, symbol: "H", name: "Hydrogen", mass: 1.008, category: "nonmetal", group: 1, period: 1 },
  { number: 2, symbol: "He", name: "Helium", mass: 4.003, category: "noble-gas", group: 18, period: 1 },
  { number: 3, symbol: "Li", name: "Lithium", mass: 6.941, category: "alkali-metal", group: 1, period: 2 },
  { number: 4, symbol: "Be", name: "Beryllium", mass: 9.012, category: "alkaline-earth", group: 2, period: 2 },
  { number: 5, symbol: "B", name: "Boron", mass: 10.81, category: "metalloid", group: 13, period: 2 },
  { number: 6, symbol: "C", name: "Carbon", mass: 12.01, category: "nonmetal", group: 14, period: 2 },
  { number: 7, symbol: "N", name: "Nitrogen", mass: 14.01, category: "nonmetal", group: 15, period: 2 },
  { number: 8, symbol: "O", name: "Oxygen", mass: 16.00, category: "nonmetal", group: 16, period: 2 },
  { number: 9, symbol: "F", name: "Fluorine", mass: 19.00, category: "halogen", group: 17, period: 2 },
  { number: 10, symbol: "Ne", name: "Neon", mass: 20.18, category: "noble-gas", group: 18, period: 2 },
  { number: 11, symbol: "Na", name: "Sodium", mass: 22.99, category: "alkali-metal", group: 1, period: 3 },
  { number: 12, symbol: "Mg", name: "Magnesium", mass: 24.31, category: "alkaline-earth", group: 2, period: 3 },
  { number: 13, symbol: "Al", name: "Aluminium", mass: 26.98, category: "post-transition", group: 13, period: 3 },
  { number: 14, symbol: "Si", name: "Silicon", mass: 28.09, category: "metalloid", group: 14, period: 3 },
  { number: 15, symbol: "P", name: "Phosphorus", mass: 30.97, category: "nonmetal", group: 15, period: 3 },
  { number: 16, symbol: "S", name: "Sulfur", mass: 32.07, category: "nonmetal", group: 16, period: 3 },
  { number: 17, symbol: "Cl", name: "Chlorine", mass: 35.45, category: "halogen", group: 17, period: 3 },
  { number: 18, symbol: "Ar", name: "Argon", mass: 39.95, category: "noble-gas", group: 18, period: 3 },
  { number: 19, symbol: "K", name: "Potassium", mass: 39.10, category: "alkali-metal", group: 1, period: 4 },
  { number: 20, symbol: "Ca", name: "Calcium", mass: 40.08, category: "alkaline-earth", group: 2, period: 4 },
  { number: 21, symbol: "Sc", name: "Scandium", mass: 44.96, category: "transition-metal", group: 3, period: 4 },
  { number: 22, symbol: "Ti", name: "Titanium", mass: 47.87, category: "transition-metal", group: 4, period: 4 },
  { number: 23, symbol: "V", name: "Vanadium", mass: 50.94, category: "transition-metal", group: 5, period: 4 },
  { number: 24, symbol: "Cr", name: "Chromium", mass: 52.00, category: "transition-metal", group: 6, period: 4 },
  { number: 25, symbol: "Mn", name: "Manganese", mass: 54.94, category: "transition-metal", group: 7, period: 4 },
  { number: 26, symbol: "Fe", name: "Iron", mass: 55.85, category: "transition-metal", group: 8, period: 4 },
  { number: 27, symbol: "Co", name: "Cobalt", mass: 58.93, category: "transition-metal", group: 9, period: 4 },
  { number: 28, symbol: "Ni", name: "Nickel", mass: 58.69, category: "transition-metal", group: 10, period: 4 },
  { number: 29, symbol: "Cu", name: "Copper", mass: 63.55, category: "transition-metal", group: 11, period: 4 },
  { number: 30, symbol: "Zn", name: "Zinc", mass: 65.38, category: "transition-metal", group: 12, period: 4 },
  { number: 31, symbol: "Ga", name: "Gallium", mass: 69.72, category: "post-transition", group: 13, period: 4 },
  { number: 32, symbol: "Ge", name: "Germanium", mass: 72.64, category: "metalloid", group: 14, period: 4 },
  { number: 33, symbol: "As", name: "Arsenic", mass: 74.92, category: "metalloid", group: 15, period: 4 },
  { number: 34, symbol: "Se", name: "Selenium", mass: 78.96, category: "nonmetal", group: 16, period: 4 },
  { number: 35, symbol: "Br", name: "Bromine", mass: 79.90, category: "halogen", group: 17, period: 4 },
  { number: 36, symbol: "Kr", name: "Krypton", mass: 83.80, category: "noble-gas", group: 18, period: 4 },
  { number: 37, symbol: "Rb", name: "Rubidium", mass: 85.47, category: "alkali-metal", group: 1, period: 5 },
  { number: 38, symbol: "Sr", name: "Strontium", mass: 87.62, category: "alkaline-earth", group: 2, period: 5 },
  { number: 47, symbol: "Ag", name: "Silver", mass: 107.9, category: "transition-metal", group: 11, period: 5 },
  { number: 53, symbol: "I", name: "Iodine", mass: 126.9, category: "halogen", group: 17, period: 5 },
  { number: 54, symbol: "Xe", name: "Xenon", mass: 131.3, category: "noble-gas", group: 18, period: 5 },
  { number: 55, symbol: "Cs", name: "Caesium", mass: 132.9, category: "alkali-metal", group: 1, period: 6 },
  { number: 56, symbol: "Ba", name: "Barium", mass: 137.3, category: "alkaline-earth", group: 2, period: 6 },
  { number: 79, symbol: "Au", name: "Gold", mass: 197.0, category: "transition-metal", group: 11, period: 6 },
  { number: 80, symbol: "Hg", name: "Mercury", mass: 200.6, category: "transition-metal", group: 12, period: 6 },
  { number: 82, symbol: "Pb", name: "Lead", mass: 207.2, category: "post-transition", group: 14, period: 6 }
];

const CATEGORY_COLORS = {
  "alkali-metal": "#fca5a5",
  "alkaline-earth": "#fdba74",
  "transition-metal": "#fde047",
  "post-transition": "#a5b4fc",
  "metalloid": "#86efac",
  "nonmetal": "#67e8f9",
  "halogen": "#c4b5fd",
  "noble-gas": "#f9a8d4"
};

const CATEGORY_LABELS = {
  "alkali-metal": "Alkali Metals",
  "alkaline-earth": "Alkaline Earth",
  "transition-metal": "Transition Metals",
  "post-transition": "Post-Transition",
  "metalloid": "Metalloids",
  "nonmetal": "Nonmetals",
  "halogen": "Halogens",
  "noble-gas": "Noble Gases"
};
