const REACTIONS = [
  {
    id: "na-cl",
    reactants: ["Na", "Cl2"],
    products: ["NaCl"],
    equation: "2 Na(s) + Cl₂(g) → 2 NaCl(s)",
    type: "Synthesis / Combination",
    explanation: "Sodium metal reacts vigorously with chlorine gas to form sodium chloride (table salt).",
    realWorld: "Bright yellow-orange flame, white smoke of salt crystals. Extremely exothermic and can be explosive if not controlled.",
    safety: "Chlorine gas is highly toxic. Sodium is water-reactive. Perform only in fume hood with proper protection.",
    visual: "Sodium atoms lose electrons to chlorine atoms, forming ionic Na⁺ and Cl⁻ which pack into a crystal lattice."
  },
  {
    id: "hcl-naoh",
    reactants: ["HCl", "NaOH"],
    products: ["NaCl", "H2O"],
    equation: "HCl(aq) + NaOH(aq) → NaCl(aq) + H₂O(l)",
    type: "Acid-Base Neutralization",
    explanation: "Strong acid and strong base neutralize each other to form a salt and water.",
    realWorld: "Solution temperature rises (exothermic). Phenolphthalein indicator changes from pink to colorless at endpoint.",
    safety: "Both HCl and NaOH are corrosive. Wear goggles and gloves.",
    visual: "H⁺ from acid combines with OH⁻ from base to form water molecules."
  },
  {
    id: "zn-hcl",
    reactants: ["Zn", "HCl"],
    products: ["ZnCl2", "H2"],
    equation: "Zn(s) + 2 HCl(aq) → ZnCl₂(aq) + H₂(g)",
    type: "Single Displacement / Redox",
    explanation: "Zinc metal displaces hydrogen from hydrochloric acid.",
    realWorld: "Bubbles of hydrogen gas form vigorously. Zinc dissolves. Solution may warm up.",
    safety: "Hydrogen gas is flammable. Perform away from flames. Acid is corrosive.",
    visual: "Zinc atoms oxidize to Zn²⁺, H⁺ ions reduce to H₂ gas."
  },
  {
    id: "agno3-nacl",
    reactants: ["AgNO3", "NaCl"],
    products: ["AgCl", "NaNO3"],
    equation: "AgNO₃(aq) + NaCl(aq) → AgCl(s) + NaNO₃(aq)",
    type: "Double Displacement / Precipitation",
    explanation: "Silver ions and chloride ions form insoluble silver chloride precipitate.",
    realWorld: "White cloudy precipitate of AgCl forms immediately and darkens on exposure to light.",
    safety: "Silver nitrate stains skin and is toxic. Avoid contact.",
    visual: "Ag⁺ and Cl⁻ ions combine to form solid AgCl lattice; Na⁺ and NO₃⁻ remain dissolved."
  },
  {
    id: "ch4-o2",
    reactants: ["CH4", "O2"],
    products: ["CO2", "H2O"],
    equation: "CH₄(g) + 2 O₂(g) → CO₂(g) + 2 H₂O(g)",
    type: "Combustion",
    explanation: "Methane burns completely in oxygen to produce carbon dioxide and water vapor.",
    realWorld: "Blue flame, heat and light released. Used in stoves and Bunsen burners.",
    safety: "Methane is flammable and can form explosive mixtures with air.",
    visual: "C–H and O=O bonds break; new C=O and O–H bonds form, releasing energy."
  },
  {
    id: "caco3-heat",
    reactants: ["CaCO3"],
    products: ["CaO", "CO2"],
    equation: "CaCO₃(s) → CaO(s) + CO₂(g)",
    type: "Thermal Decomposition",
    explanation: "Calcium carbonate decomposes on strong heating into calcium oxide and carbon dioxide.",
    realWorld: "White solid remains (quicklime). Gas evolves that turns limewater milky.",
    safety: "High temperatures required. CO₂ can displace oxygen in confined spaces.",
    visual: "Heat provides energy to break the carbonate into oxide and CO₂ gas."
  },
  {
    id: "h2-o2",
    reactants: ["H2", "O2"],
    products: ["H2O"],
    equation: "2 H₂(g) + O₂(g) → 2 H₂O(g)",
    type: "Synthesis / Combustion",
    explanation: "Hydrogen and oxygen combine explosively to form water.",
    realWorld: "Loud pop or explosion with a pale blue flame. Classic test for hydrogen gas.",
    safety: "Extremely explosive mixture. Never ignite large volumes.",
    visual: "H–H and O=O bonds break; new O–H bonds form in water molecules."
  },
  {
    id: "fe-o2",
    reactants: ["Fe", "O2"],
    products: ["Fe2O3"],
    equation: "4 Fe(s) + 3 O₂(g) → 2 Fe₂O₃(s)",
    type: "Synthesis / Oxidation",
    explanation: "Iron reacts with oxygen (often in presence of water) to form iron(III) oxide — rust.",
    realWorld: "Reddish-brown flaky rust forms slowly on iron surfaces exposed to air and moisture.",
    safety: "Generally slow at room temperature. Fine iron powder can be pyrophoric.",
    visual: "Iron atoms oxidize; oxygen reduces. Oxide layer forms on the metal surface."
  },
  {
    id: "cu-agno3",
    reactants: ["Cu", "AgNO3"],
    products: ["CuNO3", "Ag"],
    equation: "Cu(s) + 2 AgNO₃(aq) → Cu(NO₃)₂(aq) + 2 Ag(s)",
    type: "Single Displacement / Redox",
    explanation: "Copper is more reactive than silver and displaces it from silver nitrate solution.",
    realWorld: "Silver crystals or grey coating form on the copper surface. Solution turns blue.",
    safety: "Silver nitrate is toxic and staining.",
    visual: "Cu atoms oxidize to Cu²⁺; Ag⁺ ions reduce to metallic silver."
  },
  {
    id: "h2so4-naoh",
    reactants: ["H2SO4", "NaOH"],
    products: ["Na2SO4", "H2O"],
    equation: "H₂SO₄(aq) + 2 NaOH(aq) → Na₂SO₄(aq) + 2 H₂O(l)",
    type: "Acid-Base Neutralization",
    explanation: "Sulfuric acid is neutralized by sodium hydroxide.",
    realWorld: "Significant heat released. Used in titration with indicators.",
    safety: "Both reagents are highly corrosive. Always add acid to water, never reverse.",
    visual: "H⁺ ions combine with OH⁻ to form water; Na⁺ and SO₄²⁻ form the salt."
  },
  {
    id: "mg-o2",
    reactants: ["Mg", "O2"],
    products: ["MgO"],
    equation: "2 Mg(s) + O₂(g) → 2 MgO(s)",
    type: "Synthesis / Combustion",
    explanation: "Magnesium burns in air or oxygen with an intense white light to form magnesium oxide.",
    realWorld: "Brilliant white flame, white powdery residue of MgO.",
    safety: "Intense light can damage eyes. Do not look directly at the flame. Magnesium ribbon is highly flammable.",
    visual: "Magnesium atoms lose electrons to oxygen, forming ionic MgO lattice."
  },
  {
    id: "na-h2o",
    reactants: ["Na", "H2O"],
    products: ["NaOH", "H2"],
    equation: "2 Na(s) + 2 H₂O(l) → 2 NaOH(aq) + H₂(g)",
    type: "Single Displacement / Redox",
    explanation: "Sodium reacts vigorously with water to produce sodium hydroxide and hydrogen gas.",
    realWorld: "Metal skates on surface, melts into a ball, hisses, may ignite hydrogen (yellow flame).",
    safety: "Extremely vigorous. Use tiny pieces only. Hydrogen can ignite. Eye protection essential.",
    visual: "Na atoms oxidize; water is reduced, releasing H₂."
  },
  {
    id: "caco3-hcl",
    reactants: ["CaCO3", "HCl"],
    products: ["CaCl2", "CO2", "H2O"],
    equation: "CaCO₃(s) + 2 HCl(aq) → CaCl₂(aq) + CO₂(g) + H₂O(l)",
    type: "Acid-Carbonate",
    explanation: "Carbonate reacts with acid to liberate carbon dioxide.",
    realWorld: "Fizzing / effervescence as CO₂ is evolved. Solid dissolves.",
    safety: "Acid is corrosive. CO₂ is an asphyxiant in high concentration.",
    visual: "Carbonate ions react with H⁺ to form H₂CO₃ which decomposes to CO₂ + H₂O."
  },
  {
    id: "fe-hcl",
    reactants: ["Fe", "HCl"],
    products: ["FeCl2", "H2"],
    equation: "Fe(s) + 2 HCl(aq) → FeCl₂(aq) + H₂(g)",
    type: "Single Displacement / Redox",
    explanation: "Iron displaces hydrogen from hydrochloric acid.",
    realWorld: "Bubbles of hydrogen; solution turns pale green (Fe²⁺).",
    safety: "Hydrogen is flammable. Acid is corrosive.",
    visual: "Fe → Fe²⁺ + 2e⁻; 2H⁺ + 2e⁻ → H₂."
  },
  {
    id: "cuo-h2",
    reactants: ["CuO", "H2"],
    products: ["Cu", "H2O"],
    equation: "CuO(s) + H₂(g) → Cu(s) + H₂O(g)",
    type: "Redox / Reduction",
    explanation: "Hydrogen reduces copper(II) oxide to copper metal.",
    realWorld: "Black CuO turns to reddish-brown copper; steam is produced.",
    safety: "Hydrogen is flammable. Perform with care.",
    visual: "Oxygen is removed from CuO; copper ions are reduced to atoms."
  },
  {
    id: "nh3-hcl",
    reactants: ["NH3", "HCl"],
    products: ["NH4Cl"],
    equation: "NH₃(g) + HCl(g) → NH₄Cl(s)",
    type: "Acid-Base / Synthesis",
    explanation: "Ammonia and hydrogen chloride gases combine to form solid ammonium chloride.",
    realWorld: "White smoke / solid ring of NH₄Cl forms where the gases meet (classic diffusion demo).",
    safety: "Both gases are irritant. Perform in fume cupboard or with care.",
    visual: "NH₃ accepts a proton from HCl forming the ionic salt NH₄⁺Cl⁻."
  },
  {
    id: "k-h2o",
    reactants: ["K", "H2O"],
    products: ["KOH", "H2"],
    equation: "2 K(s) + 2 H₂O(l) → 2 KOH(aq) + H₂(g)",
    type: "Single Displacement / Redox",
    explanation: "Potassium reacts even more vigorously than sodium with water.",
    realWorld: "Lilac flame as hydrogen ignites; metal moves rapidly on surface.",
    safety: "Very vigorous and hazardous. Use only under specialist supervision with tiny amounts.",
    visual: "K atoms oxidize readily; water is reduced to H₂."
  },
  {
    id: "al-hcl",
    reactants: ["Al", "HCl"],
    products: ["AlCl3", "H2"],
    equation: "2 Al(s) + 6 HCl(aq) → 2 AlCl₃(aq) + 3 H₂(g)",
    type: "Single Displacement / Redox",
    explanation: "Aluminium reacts with hydrochloric acid to liberate hydrogen.",
    realWorld: "Bubbles form after an induction period (oxide layer). Solution may warm.",
    safety: "Hydrogen is flammable. Acid is corrosive.",
    visual: "Al → Al³⁺ + 3e⁻; H⁺ reduced to H₂."
  },
  {
    id: "pbno3-ki",
    reactants: ["PbNO3", "KI"],
    products: ["PbI2", "KNO3"],
    equation: "Pb(NO₃)₂(aq) + 2 KI(aq) → PbI₂(s) + 2 KNO₃(aq)",
    type: "Double Displacement / Precipitation",
    explanation: "Lead(II) ions and iodide ions form bright yellow lead(II) iodide precipitate.",
    realWorld: "Striking yellow precipitate (known as golden rain when recrystallised).",
    safety: "Lead compounds are toxic. Avoid contact and dispose of properly.",
    visual: "Pb²⁺ and I⁻ form the insoluble yellow solid PbI₂."
  },
  {
    id: "h2so4-caco3",
    reactants: ["H2SO4", "CaCO3"],
    products: ["CaSO4", "CO2", "H2O"],
    equation: "H₂SO₄(aq) + CaCO₃(s) → CaSO₄(s) + CO₂(g) + H₂O(l)",
    type: "Acid-Carbonate",
    explanation: "Sulfuric acid reacts with calcium carbonate producing sparingly soluble calcium sulfate.",
    realWorld: "Initial fizzing; reaction may slow as CaSO₄ coats the carbonate.",
    safety: "Concentrated H₂SO₄ is extremely corrosive. Dilute carefully.",
    visual: "Carbonate + acid → salt + CO₂ + water."
  },
  {
    id: "ba-so4",
    reactants: ["BaCl2", "Na2SO4"],
    products: ["BaSO4", "NaCl"],
    equation: "BaCl₂(aq) + Na₂SO₄(aq) → BaSO₄(s) + 2 NaCl(aq)",
    type: "Double Displacement / Precipitation",
    explanation: "Barium sulfate is highly insoluble and forms a dense white precipitate.",
    realWorld: "White precipitate used as a test for sulfate ions.",
    safety: "Barium compounds are toxic if soluble.",
    visual: "Ba²⁺ and SO₄²⁻ combine to form insoluble BaSO₄ lattice."
  },
  {
    id: "fecl3-naoh",
    reactants: ["FeCl3", "NaOH"],
    products: ["FeOH3", "NaCl"],
    equation: "FeCl₃(aq) + 3 NaOH(aq) → Fe(OH)₃(s) + 3 NaCl(aq)",
    type: "Double Displacement / Precipitation",
    explanation: "Iron(III) hydroxide forms a characteristic brown gelatinous precipitate.",
    realWorld: "Brown precipitate of Fe(OH)₃.",
    safety: "FeCl₃ is corrosive and stains.",
    visual: "Fe³⁺ + 3OH⁻ → Fe(OH)₃(s)."
  },
  {
    id: "cuso4-naoh",
    reactants: ["CuSO4", "NaOH"],
    products: ["CuOH2", "Na2SO4"],
    equation: "CuSO₄(aq) + 2 NaOH(aq) → Cu(OH)₂(s) + Na₂SO₄(aq)",
    type: "Double Displacement / Precipitation",
    explanation: "Copper(II) hydroxide is a blue gelatinous precipitate.",
    realWorld: "Pale blue precipitate forms immediately.",
    safety: "Copper compounds can be toxic in large amounts.",
    visual: "Cu²⁺ + 2OH⁻ → Cu(OH)₂(s)."
  },
  {
    id: "thermite",
    reactants: ["Al", "Fe2O3"],
    products: ["Al2O3", "Fe"],
    equation: "2 Al(s) + Fe₂O₃(s) → Al₂O₃(s) + 2 Fe(l)",
    type: "Redox / Thermite",
    explanation: "Highly exothermic displacement reaction used in welding.",
    realWorld: "Intense heat, molten iron produced. Classic thermite demonstration.",
    safety: "Extremely high temperatures. Specialist supervision only.",
    visual: "Al reduces Fe³⁺ to Fe metal; Al is oxidized to Al₂O₃."
  },
  {
    id: "haber",
    reactants: ["N2", "H2"],
    products: ["NH3"],
    equation: "N₂(g) + 3 H₂(g) ⇌ 2 NH₃(g)",
    type: "Synthesis (Haber Process)",
    explanation: "Industrial synthesis of ammonia under high pressure and temperature with catalyst.",
    realWorld: "Critical for fertilizer production worldwide.",
    safety: "High pressure industrial process.",
    visual: "N≡N and H–H bonds break; N–H bonds form."
  },
  {
    id: "h2o2-decomp",
    reactants: ["H2O2"],
    products: ["H2O", "O2"],
    equation: "2 H₂O₂(aq) → 2 H₂O(l) + O₂(g)",
    type: "Decomposition",
    explanation: "Hydrogen peroxide decomposes, accelerated by catalysts (MnO₂, catalase).",
    realWorld: "Bubbles of oxygen. Elephant’s toothpaste demo when concentrated + catalyst.",
    safety: "Concentrated H₂O₂ is corrosive and oxidizing.",
    visual: "O–O bond breaks; oxygen gas is released."
  },
  {
    id: "ethanol-combustion",
    reactants: ["C2H5OH", "O2"],
    products: ["CO2", "H2O"],
    equation: "C₂H₅OH(l) + 3 O₂(g) → 2 CO₂(g) + 3 H₂O(g)",
    type: "Combustion",
    explanation: "Complete combustion of ethanol.",
    realWorld: "Blue flame, heat and CO₂/H₂O produced. Used in spirit burners.",
    safety: "Ethanol is flammable.",
    visual: "C–C, C–H, O=O bonds rearrange to C=O and O–H."
  },
  {
    id: "esterification",
    reactants: ["CH3COOH", "C2H5OH"],
    products: ["CH3COOC2H5", "H2O"],
    equation: "CH₃COOH + C₂H₅OH ⇌ CH₃COOC₂H₅ + H₂O",
    type: "Organic (Esterification)",
    explanation: "Acid-catalyzed condensation of carboxylic acid and alcohol to form ester.",
    realWorld: "Fruity smell of ethyl ethanoate.",
    safety: "Concentrated acid catalyst is corrosive.",
    visual: "–OH from acid and –H from alcohol eliminated as water; ester linkage forms."
  },
  {
    id: "ethene-hydration",
    reactants: ["C2H4", "H2O"],
    products: ["C2H5OH"],
    equation: "C₂H₄(g) + H₂O(g) → C₂H₅OH(g)",
    type: "Organic (Addition / Hydration)",
    explanation: "Industrial production of ethanol by hydration of ethene.",
    realWorld: "Major industrial route to ethanol.",
    safety: "High temperature/pressure process.",
    visual: "π-bond of ethene opens; H and OH add across the double bond."
  },
  {
    id: "methane-chlorination",
    reactants: ["CH4", "Cl2"],
    products: ["CH3Cl", "HCl"],
    equation: "CH₄ + Cl₂ → CH₃Cl + HCl",
    type: "Organic (Free-radical Substitution)",
    explanation: "UV-initiated free-radical chlorination of methane.",
    realWorld: "First step in a mixture of chloromethanes.",
    safety: "Chlorine is toxic; UV light required.",
    visual: "Homolytic cleavage of Cl–Cl; radical chain reaction."
  },
  {
    id: "so3-h2o",
    reactants: ["SO3", "H2O"],
    products: ["H2SO4"],
    equation: "SO₃(g) + H₂O(l) → H₂SO₄(aq)",
    type: "Synthesis / Acid Formation",
    explanation: "Sulfur trioxide reacts with water to form sulfuric acid (Contact process final stage).",
    realWorld: "Highly exothermic; industrial production of H₂SO₄.",
    safety: "SO₃ and concentrated H₂SO₄ are extremely corrosive.",
    visual: "SO₃ accepts water to form the acid."
  },
  {
    id: "mg-hcl",
    reactants: ["Mg", "HCl"],
    products: ["MgCl2", "H2"],
    equation: "Mg(s) + 2 HCl(aq) → MgCl₂(aq) + H₂(g)",
    type: "Single Displacement / Redox",
    explanation: "Magnesium reacts readily with dilute hydrochloric acid.",
    realWorld: "Rapid bubbling of hydrogen; metal dissolves; solution warms.",
    safety: "Hydrogen is flammable. Acid is corrosive.",
    visual: "Mg → Mg²⁺ + 2e⁻; 2H⁺ + 2e⁻ → H₂."
  },
  {
    id: "cuo-h2so4",
    reactants: ["CuO", "H2SO4"],
    products: ["CuSO4", "H2O"],
    equation: "CuO(s) + H₂SO₄(aq) → CuSO₄(aq) + H₂O(l)",
    type: "Acid-Base (Metal Oxide)",
    explanation: "Copper(II) oxide is a basic oxide and reacts with acid to form a salt and water.",
    realWorld: "Black solid dissolves forming blue CuSO₄ solution.",
    safety: "Acid is corrosive.",
    visual: "Oxide ion combines with H⁺ to form water; Cu²⁺ and SO₄²⁻ remain in solution."
  },
  {
    id: "nahco3-heat",
    reactants: ["NaHCO3"],
    products: ["Na2CO3", "H2O", "CO2"],
    equation: "2 NaHCO₃(s) → Na₂CO₃(s) + H₂O(g) + CO₂(g)",
    type: "Thermal Decomposition",
    explanation: "Sodium hydrogen carbonate decomposes on heating.",
    realWorld: "Used in baking powder; CO₂ causes rising.",
    safety: "Generally safe at moderate temperatures.",
    visual: "Heat drives off water and CO₂ leaving the carbonate."
  }
];

const REACTANT_OPTIONS = [
  { id: "Na", label: "Sodium (Na)" },
  { id: "Cl2", label: "Chlorine (Cl₂)" },
  { id: "HCl", label: "Hydrochloric acid (HCl)" },
  { id: "NaOH", label: "Sodium hydroxide (NaOH)" },
  { id: "Zn", label: "Zinc (Zn)" },
  { id: "AgNO3", label: "Silver nitrate (AgNO₃)" },
  { id: "NaCl", label: "Sodium chloride (NaCl)" },
  { id: "CH4", label: "Methane (CH₄)" },
  { id: "O2", label: "Oxygen (O₂)" },
  { id: "CaCO3", label: "Calcium carbonate (CaCO₃)" },
  { id: "H2", label: "Hydrogen (H₂)" },
  { id: "Fe", label: "Iron (Fe)" },
  { id: "Cu", label: "Copper (Cu)" },
  { id: "H2SO4", label: "Sulfuric acid (H₂SO₄)" },
  { id: "Mg", label: "Magnesium (Mg)" },
  { id: "H2O", label: "Water (H₂O)" },
  { id: "CuO", label: "Copper(II) oxide (CuO)" },
  { id: "NH3", label: "Ammonia (NH₃)" },
  { id: "K", label: "Potassium (K)" },
  { id: "Al", label: "Aluminium (Al)" },
  { id: "PbNO3", label: "Lead(II) nitrate (Pb(NO₃)₂)" },
  { id: "KI", label: "Potassium iodide (KI)" },
  { id: "BaCl2", label: "Barium chloride (BaCl₂)" },
  { id: "Na2SO4", label: "Sodium sulfate (Na₂SO₄)" },
  { id: "FeCl3", label: "Iron(III) chloride (FeCl₃)" },
  { id: "CuSO4", label: "Copper(II) sulfate (CuSO₄)" },
  { id: "Fe2O3", label: "Iron(III) oxide (Fe₂O₃)" },
  { id: "N2", label: "Nitrogen (N₂)" },
  { id: "H2O2", label: "Hydrogen peroxide (H₂O₂)" },
  { id: "C2H5OH", label: "Ethanol (C₂H₅OH)" },
  { id: "CH3COOH", label: "Ethanoic acid (CH₃COOH)" },
  { id: "C2H4", label: "Ethene (C₂H₄)" },
  { id: "SO3", label: "Sulfur trioxide (SO₃)" },
  { id: "NaHCO3", label: "Sodium hydrogen carbonate (NaHCO₃)" }
];
